name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android App with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile=production --non-interactive
          # After build completes, get the download URL for the artifact
          # This command outputs the latest build info as JSON
          eas build:list --platform android --limit 1 --json > build-info.json

      - name: Download APK from EAS
        run: |
          # Extract the artifact URL from the build-info.json
          ARTIFACT_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
          echo "Downloading APK from $ARTIFACT_URL"
          curl -o app-release.apk "$ARTIFACT_URL"

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          file: app-release.apk
          groups: testers
          releaseNotes: "Automated build from GitHub Actions"
