name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android App with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile=production --non-interactive

      - name: Get latest EAS Android build info
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build:list --platform android --limit 1 --json > build-info.json

      - name: Install jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download Android artifact from EAS
        run: |
          ARTIFACT_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
          echo "Artifact URL: $ARTIFACT_URL"
          # Download as .aab (default for EAS), rename if you use APK
          curl -o app-release.aab "$ARTIFACT_URL"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute app-release.aab \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "testers" \
            --release-notes "Automated build from GitHub Actions"
